var KEY="35-iris-iphone-v1";
var QUESTIONS=[
  {id:"devices",q:"Apple ID → Devices: is there a phone, iPad, or Mac you do not own?",path:"Settings → [your name] → scroll to Devices",yes:"C",no:"A",idk:"B"},
  {id:"mdm",q:"Is there a configuration profile or MDM you did not install?",path:"Settings → General → VPN & Device Management",yes:"C",no:"A",idk:"B"},
  {id:"ext",q:"Does Safari have an extension you do not remember installing?",path:"Settings → Apps → Safari → Extensions",yes:"B",no:"A",idk:"B"},
  {id:"chat",q:"Is a second phone or browser linked to WhatsApp / iMessage / Telegram?",path:"WhatsApp → Settings → Linked devices",yes:"C",no:"A",idk:"B"},
  {id:"mail",q:"Does any mail account forward to an address you did not set?",path:"Gmail / iCloud Mail forwarding. Visual only.",yes:"C",no:"A",idk:"B"},
  {id:"screen",q:"Is Screen Time / Screen Sharing / a remote-view app on that you did not turn on?",path:"Settings → Screen Time · Apps you do not know",yes:"C",no:"A",idk:"B"}
];
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||"{}");}catch(e){return {};}}
function saveState(s){try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){}}
function rank(answers){var cls="A",notes=[];QUESTIONS.forEach(function(item){var a=answers[item.id];if(!a){if(cls==="A")cls="B";notes.push(item.id+": unanswered");return;}if(a==="yes"){if(item.yes==="C")cls="C";else if(item.yes==="B"&&cls==="A")cls="B";notes.push(item.id+": YES");}else if(a==="idk"){if(cls==="A")cls="B";notes.push(item.id+": open the path");}else notes.push(item.id+": no");});return{cls:cls,notes:notes};}
function nextText(cls){if(cls==="A")return "Device looks quiet from what you tapped. Record the date. Do not install a cleaner.";if(cls==="B")return "Open the yellow paths now. If a name appears you cannot explain, treat it as C.";return "Stop. Remove the unknown device / profile / linked session YOURSELF. Change Apple ID password on this phone. Do not mail a seed.";}
function renderIphone(){var root=document.getElementById("iphone");if(!root)return;var answers=(loadState().answers)||{};var html="";QUESTIONS.forEach(function(item){var cur=answers[item.id]||"";html+='<div class="card">';html+='<p class="path">'+item.path+"</p>";html+='<p class="q">'+item.q+'</p><div class="ans">';["no","yes","idk"].forEach(function(v){var label=v==="idk"?"not sure":v;var on=cur===v?" on-"+v:"";html+='<button type="button" data-id="'+item.id+'" data-v="'+v+'" class="'+on.trim()+'">'+label+"</button>";});html+="</div></div>";});var r=rank(answers);html+='<div class="card"><span class="badge '+r.cls+'">CLASS '+r.cls+"</span>";html+='<p class="rule">'+nextText(r.cls)+"\n"+r.notes.join("\n")+"</p>";html+='<div class="row"><button class="ghost" id="reset-iphone" type="button">Reset answers</button></div></div>';root.innerHTML=html;root.querySelectorAll(".ans button").forEach(function(b){b.onclick=function(){var s=loadState();s.answers=s.answers||{};s.answers[b.getAttribute("data-id")]=b.getAttribute("data-v");s.updated=new Date().toISOString();saveState(s);renderIphone();};});var reset=document.getElementById("reset-iphone");if(reset)reset.onclick=function(){saveState({answers:{},updated:new Date().toISOString()});renderIphone();};}
var tabI=document.getElementById("tab-iphone"),tabS=document.getElementById("tab-sig");
if(tabI)tabI.onclick=function(){tabI.classList.add("on");tabS.classList.remove("on");document.getElementById("iphone").classList.add("on");document.getElementById("sig").classList.remove("on");};
if(tabS)tabS.onclick=function(){tabS.classList.add("on");tabI.classList.remove("on");document.getElementById("sig").classList.add("on");document.getElementById("iphone").classList.remove("on");};
renderIphone();
var ALLOW={"11111111111111111111111111111111":"System","TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA":"SPL Token","TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb":"Token-2022","ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL":"ATA","ComputeBudget111111111111111111111111111111":"ComputeBudget","MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr":"Memo"};
var MAX="18446744073709551615";
var RPCS=["https://api.mainnet-beta.solana.com","https://solana-rpc.publicnode.com"];
function looksSecret(s){var t=s.trim();if(/\b(\w+\s+){11,23}\w+\b/.test(t)&&t.split(/\s+/).length<=24)return true;if(/^\s*\[[\d,\s]{80,}\]\s*$/.test(t))return true;return false;}
function looksSig(s){return /^[1-9A-HJ-NP-Za-km-z]{64,88}$/.test(s.trim());}
function ixList(tx){var outer=tx.transaction.message.instructions||[];var inner=[];(tx.meta&&tx.meta.innerInstructions||[]).forEach(function(g){(g.instructions||[]).forEach(function(ix){inner.push(ix);});});return outer.concat(inner);}
function classify(tx){var ixs=ixList(tx),programs=[],notes=[],cls="A";ixs.forEach(function(ix){var pid=String(ix.programId||"");var name=ALLOW[pid]||"UNKNOWN";if(programs.indexOf(name==="UNKNOWN"?pid:name)<0)programs.push(name==="UNKNOWN"?pid.slice(0,8)+"\u2026":name);if(!ALLOW[pid]&&pid.length>20){cls="C";notes.push("unknown program "+pid);}var parsed=ix.parsed||null;var typ=parsed&&parsed.type?parsed.type:"";var info=parsed&&parsed.info?parsed.info:{};var amt=info.amount||info.lamports||(info.tokenAmount&&info.tokenAmount.amount);if(typ==="approve"||typ==="approveChecked"){if(String(amt)===MAX){if(cls!=="C")cls="B";notes.push("unlimited approve");}else notes.push("finite approve");}if(typ==="setAuthority"){cls="C";notes.push("SetAuthority");}});if(!ixs.length){cls="C";notes.push("no instructions");}return{cls:cls,programs:programs,notes:notes};}
function show(cls,text){var out=document.getElementById("out");if(!out)return;out.classList.add("on");var badge=document.getElementById("badge");badge.className="badge "+cls;badge.textContent=cls==="X"?"BLOCKED":"CLASS "+cls;document.getElementById("report").textContent=text;}
async function rpcGet(sig){var body=JSON.stringify({jsonrpc:"2.0",id:1,method:"getTransaction",params:[sig,{encoding:"jsonParsed",maxSupportedTransactionVersion:0}]});var last=null;for(var i=0;i<RPCS.length;i++){try{var res=await fetch(RPCS[i],{method:"POST",headers:{"content-type":"application/json"},body:body});var j=await res.json();if(j.result)return j.result;last=(j.error&&j.error.message)||"empty";}catch(e){last=String(e.message||e);}}throw new Error(last||"rpc failed");}
var run=document.getElementById("run");
if(run)run.onclick=async function(){var raw=document.getElementById("q").value||"";if(looksSecret(raw)){show("X","Rejected. Looks like a seed.");document.getElementById("q").value="";return;}var sig=raw.trim();if(!looksSig(sig)){show("X","Need a public signature.");return;}show("X","Reading chain...");try{var tx=await rpcGet(sig);if(!tx){show("C","Not found.");return;}var r=classify(tx);var lines=["programs "+(r.programs.join(", ")||"none")].concat(r.notes.map(function(n){return "- "+n;}));if(r.cls==="B")lines.push("next: revoke in YOUR wallet");if(r.cls==="C")lines.push("next: do not sign twins");show(r.cls,lines.join("\n"));}catch(e){show("C","RPC blocked. Mail only the public signature.");}};
var clr=document.getElementById("clr");
if(clr)clr.onclick=function(){document.getElementById("q").value="";document.getElementById("out").classList.remove("on");};
